### ISSUE TITLE
createcoverage causing Travis CI timeouts?

### ISSUE THREAD

**Issue by hvelarde** [reinout/createcoverage#5]
Some weeks ago we started experiencing issues with Travis CI builds timeouts because "something" was left behind; @mauritsvanrees developed a workaround that consists on killing the Firefox browser after running tests.

I was checking the output of one of the builds and I discovered the following:

```console
$ pkill -9 firefox
Done. Your build exited with 0.
Killed
/usr/bin/xdg-open: 461: /usr/bin/xdg-open: mozilla: not found
/usr/bin/xdg-open: 461: /usr/bin/xdg-open: epiphany: not found
/usr/bin/xdg-open: 461: /usr/bin/xdg-open: konqueror: not found
[4017:4017:1220/201932:FATAL:setuid_sandbox_client.cc(282)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /usr/lib/chromium-browser/chrome-sandbox is owned by root and has mode 4755.
Aborted (core dumped)
/usr/bin/xdg-open: 461: /usr/bin/xdg-open: google-chrome: not found
/usr/bin/xdg-open: 461: /usr/bin/xdg-open: links2: not found
/usr/bin/xdg-open: 461: /usr/bin/xdg-open: links: not found
/usr/bin/xdg-open: 461: /usr/bin/xdg-open: lynx: not found
/usr/bin/xdg-open: 461: /usr/bin/xdg-open: w3m: not found
xdg-open: no method available for opening 'file:///home/travis/build/collective/sc.social.like/htmlcov/index.html'
```

so the primary suspect here is `createcoverage`, even as this is something more likely related with a bug on Travis CI containers management (see https://github.com/travis-ci/travis-ci/issues/6861).

do you think is possible to add an option to avoid opening the coverage report at the end?

https://github.com/reinout/createcoverage/blob/master/createcoverage/script.py#L89-L94

**Comment by mauritsvanrees** [comment]
From looking at that code, using `--output-dir=/some/dir` should help.

**Comment by mauritsvanrees** [comment]
In `qa.cfg` in `buildout.plonetest`, which is used by a lot of Plone add-ons, we should use the `--output-dir` option. I have made a pull request in that repo. So I will close this issue.
